### ISSUE TITLE
I Want a General Overview of the AaC Packages in the Dev Docs

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#471]
As an AaC dev, I want a general overview of the AaC packages in the developer docs, so that new developers and plugin developers can easily look up the overview and organization of AaC features and code.

## AC:
- [x] There is a new page in the developer docs that describes the overall structure of the AaC project, and the features/focus for the various packages in AaC. 
  - [x] i.e. cli, io, lang, etc. 
  - [x] This is NOT deep dive explanations of each of these packages, but the relationship between the packages within the AaC project structure.

**Comment by lizzcondrey** [comment]
Removed last AC because the structure is about to go through a change when we refactor underlying systems, so the extra effort of generating the model and graphics does not make much sense to do right now. But the components and their roles are staying close to the same, so the documentation could be updated.
